### ISSUE TITLE
Add shape-files for shelf-boxes

### ISSUE THREAD

**Issue by stefan2904** [realraum/furniture#1]
- [ ] create folder for shelf?
- [ ] create folder for this shapefiles
- [ ] copy from http://2904.cc/realraum/kiste/ 
- [ ] dont forget "license"
- [ ] Bonus: add description & HowTo?

**Comment by trapicki** [comment]
Am 08.09.2015 um 18:47 schrieb Stefan:

> - create folder for shelf?

done.

> - create folder for this shapefiles
> - copy from http://2904.cc/realraum/kiste/
> - dont forget "license"

Angelas Datei hab ich irrtümlich auch hochgeladen. Ihre Lizenz passt 
somit nicht, gehört in ein eigenes Verzeichnis mit extra-Lizenz.

Wenn du (Stefan) das schnell hinbekommst brauch ich mich nicht durch das 
git-Moven durchplagen, bin da nicht so gut.

## Patrick

Engineers motto: cheap, good, fast - choose any two
One of the lucky 10.000: http://xkcd.com/1053
Use Mail Encryption Today! PGP Key ID: 0xDF8A127E5A120903
Patrick Strasser patrick@wirklich.priv.at

**Comment by stefan2904** [comment]
Hast aber noch nicht gepusht?
Dann push das mal nicht, nimms wieder raus, und ich mach das.

Die Issue war eh auf mich assigned ... ;-)

**Comment by trapicki** [comment]
Am 08.09.2015 um 19:26 schrieb Stefan:

> Hast aber noch nicht gepusht?
> Dann push das mal nicht, nimms wieder raus, und ich mach das.
> 
> Die Issue war eh auf mich assigned ... ;-)

Nein, hab ich noch nicht gepushed. Siehst du, so viel Praxis hab ich mit 
Github...

Ich hab selber was gemacht, mit den oberen drei Feldern dazu, von einem 
Foto nachgezeichnet.

Ich schick dir das jetzt einmal einfach mit, und du machst was schönes 
daraus.

Für die in diesem Mail mitgeschickten Dateien, die ich gemacht habe, CC0 
als Lizenz.

LG

## Patrick

Engineers motto: cheap, good, fast - choose any two
One of the lucky 10.000: http://xkcd.com/1053
Use Mail Encryption Today! PGP Key ID: 0xDF8A127E5A120903
Patrick Strasser patrick@wirklich.priv.at

**Comment by stefan2904** [comment]
solved in 8e000dda7432052f6f4cf45f851341d9cc982700
